# generated by datamodel-codegen:
#   filename:  gerund_or_infinitive.schema.json
#   timestamp: 2024-09-10T18:46:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class FollowedByEnum(str, Enum):
    gerund = 'gerund'
    infinitive = 'infinitive'
    bare_infinitive = 'bare_infinitive'


class GerundOrInfinitiveItem(BaseModel):
    verb: str = Field(..., description='Corresponding verb')
    followed_by: List[FollowedByEnum] = Field(
        ..., description='What follows the verb', min_length=1
    )


class GerundOrInfinitive(RootModel[Optional[Dict[str, GerundOrInfinitiveItem]]]):
    root: Optional[Dict[str, GerundOrInfinitiveItem]] = None
